import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Plane, Map, CalendarDays, ListChecks, Users, Settings, Plus, Sparkles, Wallet, Hotel, Train, FileCheck, Route, CheckCircle2, Circle, ChevronRight, ArrowLeft, Luggage, Utensils, MapPin, Clock, Trash2} from 'lucide-react';
import './style.css';

const emptyTrip={name:'',destination:'',start:'',end:'',budget:0,itinerary:[],checklist:[],expenses:[]};
const stages=[['Destino e datas',Map],['Orçamento',Wallet],['Transporte',Train],['Hospedagem',Hotel],['Documentos',FileCheck],['Roteiro diário',Route],['Reservas',CalendarDays],['Viagem em grupo',Users],['Mala e preparação',Luggage]];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);

function App(){
 const [trip,setTrip]=useState(()=>JSON.parse(localStorage.getItem('tripnext-trip')||'null'));
 const [tab,setTab]=useState('inicio'); const [modal,setModal]=useState(null); const [planner,setPlanner]=useState(false);
 useEffect(()=>trip?localStorage.setItem('tripnext-trip',JSON.stringify(trip)):localStorage.removeItem('tripnext-trip'),[trip]);
 const update=patch=>setTrip(t=>({...t,...patch}));
 if(!trip) return <><Empty onCreate={()=>setModal('trip')}/>{modal==='trip'&&<TripModal onClose={()=>setModal(null)} onSave={t=>{setTrip({...emptyTrip,...t});setModal(null)}}/>}</>;
 const dialogs=<>{modal==='event'&&<EventModal trip={trip} onClose={()=>setModal(null)} onSave={e=>{update({itinerary:[...trip.itinerary,e]});setModal(null)}}/>}{modal==='task'&&<TaskModal onClose={()=>setModal(null)} onSave={x=>{update({checklist:[...trip.checklist,x]});setModal(null)}}/>}{modal==='trip'&&<TripModal onClose={()=>setModal(null)} onSave={t=>{setTrip({...emptyTrip,...t});setModal(null)}}/>}</>;
 if(planner) return <><Planner trip={trip} setTrip={setTrip} close={()=>setPlanner(false)} open={setModal}/>{dialogs}</>;
 return <><div className="shell"><Sidebar tab={tab} setTab={setTab}/><main>{tab==='inicio'&&<Home trip={trip} planner={()=>setPlanner(true)} open={setModal}/>} {tab==='itinerario'&&<Itinerary trip={trip} open={setModal}/>} {tab==='checklist'&&<Checklist trip={trip} update={update} open={setModal}/>} {tab==='grupo'&&<Group/>} {tab==='ajustes'&&<SettingsPage trip={trip} remove={()=>{if(confirm('Excluir esta viagem e todos os dados?'))setTrip(null)}}/>}</main></div>{dialogs}</>;
}
function Sidebar({tab,setTab}){const items=[['inicio','Início',Map],['itinerario','Itinerário',CalendarDays],['checklist','Checklist',ListChecks],['grupo','Grupo',Users],['ajustes','Ajustes',Settings]];return <aside><div className="brand"><span><Plane/></span><b>TripNext</b></div><nav>{items.map(([id,l,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/>{l}</button>)}</nav><div className="profile"><i>J</i><div><b>Jefferson</b><small>Planejando</small></div></div></aside>}
function Empty({onCreate}){return <div className="empty"><div className="empty-card"><span className="big-icon"><Map/></span><p className="eyebrow">TRIPNEXT</p><h1>Para onde vamos agora?</h1><p>Crie uma viagem e organize roteiro, reservas, orçamento, documentos e mala em um só lugar.</p><button className="primary" onClick={onCreate}><Plus/> Planejar nova viagem</button></div></div>}
function Home({trip,planner,open}){const spent=trip.expenses.reduce((a,e)=>a+Number(e.value),0);return <div className="page"><Header title={`Boa viagem, Jefferson`} subtitle={trip.name} action={<button className="outline" onClick={()=>open('trip')}><Plus/> Nova viagem</button>}/><section className="boarding"><div><small>PRÓXIMA VIAGEM</small><h2>{trip.name}</h2><p>{trip.destination}</p></div><Plane/><div className="dates">{pretty(trip.start)} — {pretty(trip.end)}</div><div className="barcode"/></section><div className="grid two"><Card className="plan-card" onClick={planner}><div className="card-title"><span><Map/></span><div><h3>Plano da viagem</h3><p>Continue de onde parou</p></div><b>33%</b><ChevronRight/></div><Progress value={33}/><small>PRÓXIMA DECISÃO</small><strong>Montar o primeiro dia</strong></Card><Card><div className="card-title"><span><Wallet/></span><div><h3>Orçamento</h3><p>{money(spent)} de {money(trip.budget)}</p></div><b>{trip.budget?Math.round(spent/trip.budget*100):0}%</b></div><Progress value={trip.budget?spent/trip.budget*100:0}/><small>RESTANTE</small><strong>{money(trip.budget-spent)}</strong></Card></div><h3 className="section-title">Planejamento rápido</h3><div className="quick"><Quick icon={CalendarDays} title="Roteiro" text={`${trip.itinerary.length} eventos`} onClick={()=>open('event')}/><Quick icon={ListChecks} title="Preparação" text={`${trip.checklist.length} tarefas`} onClick={()=>open('task')}/><Quick icon={Sparkles} title="Copiloto IA" text="Gerar sugestões" onClick={planner}/></div></div>}
function Header({title,subtitle,action}){return <header><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>}
function Card({children,className='',onClick}){return <section className={'card '+className} onClick={onClick}>{children}</section>}
function Progress({value}){return <div className="progress"><i style={{width:`${Math.min(100,value)}%`}}/></div>}
function Quick({icon:I,title,text,onClick}){return <button className="quick-card" onClick={onClick}><span><I/></span><div><b>{title}</b><small>{text}</small></div><ChevronRight/></button>}
function Planner({trip,setTrip,close,open}){const done=trip.itinerary.length?4:3;return <div className="full-page"><header><button className="icon" onClick={close}><ArrowLeft/></button><div><h1>Planejar viagem</h1><p>{trip.name}</p></div><button className="ai"><Sparkles/> Copiloto</button></header><Card className="hero"><p className="eyebrow">PREPARAÇÃO GERAL <b>{done}/9</b></p><h2>Sua viagem está tomando forma</h2><Progress value={done/9*100}/></Card><div className="planner-grid"><div><h3 className="section-title">Prioridades agora</h3><div className="alert"><b>Completar o roteiro</b><p>Organize manhã, tarde e noite de cada dia.</p></div><div className="alert orange"><b>Confirmar hospedagem</b><p>Salve endereço, check-in e cancelamento.</p></div></div><div><h3 className="section-title">Etapas</h3><div className="stage-list">{stages.map(([name,I],idx)=><button key={name} onClick={()=>idx===5?open('event'):idx===8?open('task'):null}><span><I/></span><div><b>{name}</b><small>{idx<done?'Encaminhado':'Pendente'}</small></div>{idx<done?<CheckCircle2 className="ok"/>:<Circle/>}</button>)}</div></div></div>{modalFor(open,trip,setTrip)}</div>}
function Itinerary({trip,open}){return <div className="page"><Header title="Itinerário" subtitle={trip.name} action={<button className="primary small" onClick={()=>open('event')}><Plus/> Adicionar</button>}/>{trip.itinerary.length===0?<Blank icon={CalendarDays} title="Seu roteiro está vazio" text="Adicione voos, reservas, passeios e deslocamentos." action={()=>open('event')}/>:<div className="timeline">{trip.itinerary.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map((e,i)=><article key={i}><time>{e.time}<small>{pretty(e.date)}</small></time><span><MapPin/></span><Card><h3>{e.title}</h3><p>{e.location||'Local a definir'}</p></Card></article>)}</div>}{modalFor(open,trip,null)}</div>}
function Checklist({trip,update,open}){const toggle=i=>update({checklist:trip.checklist.map((x,n)=>n===i?{...x,done:!x.done}:x)});return <div className="page"><Header title="Checklist" subtitle={`${trip.checklist.filter(x=>x.done).length}/${trip.checklist.length} concluído`} action={<button className="primary small" onClick={()=>open('task')}><Plus/> Adicionar</button>}/>{trip.checklist.length===0?<Blank icon={ListChecks} title="Nada por aqui ainda" text="Crie tarefas de documentos, reservas e mala." action={()=>open('task')}/>:<Card className="list">{trip.checklist.map((x,i)=><button onClick={()=>toggle(i)} key={i}>{x.done?<CheckCircle2 className="ok"/>:<Circle/>}<div><b className={x.done?'done':''}>{x.name}</b><small>{x.category}</small></div></button>)}</Card>}{modalFor(open,trip,null)}</div>}
function Group(){return <div className="page"><Header title="Viagem em grupo" subtitle="Convites, divisão de despesas e decisões"/><Blank icon={Users} title="Viajar é melhor junto" text="Convide participantes quando criar sua próxima viagem."/></div>}
function SettingsPage({trip,remove}){return <div className="page"><Header title="Ajustes" subtitle="Preferências do TripNext"/><Card className="settings"><div><b>Tema</b><span>Web · Claro</span></div><div><b>Moeda</b><span>BRL</span></div><div><b>Sincronização</b><span>Local</span></div></Card><button className="danger" onClick={remove}><Trash2/> Excluir {trip.name}</button></div>}
function Blank({icon:I,title,text,action}){return <div className="blank"><span><I/></span><h2>{title}</h2><p>{text}</p>{action&&<button className="outline" onClick={action}><Plus/> Adicionar</button>}</div>}
function TripModal({onClose,onSave}){const [f,setF]=useState({name:'',destination:'',start:'',end:'',budget:''});return <Modal title="Planejar nova viagem" close={onClose}><div className="fields"><label>Nome da viagem<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Férias em Portugal"/></label><label>Destino<input value={f.destination} onChange={e=>setF({...f,destination:e.target.value})} placeholder="Lisboa e Porto"/></label><div><label>Ida<input type="date" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></label><label>Volta<input type="date" value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></label></div><label>Orçamento total<input type="number" value={f.budget} onChange={e=>setF({...f,budget:e.target.value})} placeholder="8500"/></label><button className="primary" disabled={!f.name||!f.destination||!f.start||!f.end} onClick={()=>onSave({...f,budget:Number(f.budget)})}>Criar plano da viagem</button></div></Modal>}
function EventModal({trip,onClose,onSave}){const [f,setF]=useState({title:'',location:'',date:trip.start,time:'09:00'});return <Modal title="Novo compromisso" close={onClose}><div className="fields"><label>Título<input value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Voo, passeio, reserva..."/></label><label>Local<input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></label><div><label>Data<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Horário<input type="time" value={f.time} onChange={e=>setF({...f,time:e.target.value})}/></label></div><button className="primary" disabled={!f.title||!f.date} onClick={()=>onSave(f)}>Adicionar ao itinerário</button></div></Modal>}
function TaskModal({onClose,onSave}){const [name,setName]=useState('');const [category,setCategory]=useState('Documentos');return <Modal title="Nova tarefa" close={onClose}><div className="fields"><label>O que precisa preparar?<input value={name} onChange={e=>setName(e.target.value)} placeholder="Verificar passaporte"/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option>Documentos</option><option>Reservas</option><option>Mala</option><option>Saúde</option><option>Eletrônicos</option></select></label><button className="primary" disabled={!name} onClick={()=>onSave({name,category,done:false})}>Adicionar ao checklist</button></div></Modal>}
function Modal({title,close,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function modalFor(open,trip,setTrip){return null}
function pretty(d){if(!d)return 'Data a definir';return new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','')}
createRoot(document.getElementById('root')).render(<App/>);
